/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        coral: {
          DEFAULT: "#cc785c",
          active: "#a9583e",
        },
        "accent-teal": "#5db8a6",
        "accent-amber": "#e8a55a",
        canvas: "#faf9f5",
        "surface-soft": "#f5f0e8",
        "surface-card": "#efe9de",
        "surface-cream-strong": "#e8e0d2",
        "surface-dark": "#181715",
        "surface-dark-elevated": "#252320",
        "surface-dark-soft": "#1f1e1b",
        hairline: "#e6dfd8",
        "hairline-soft": "#ebe6df",
        ink: "#141413",
        "body-strong": "#252523",
        body: "#3d3d3a",
        muted: "#8e8b82",
        "muted-soft": "#8e8b82",
        "on-primary": "#ffffff",
        "on-dark": "#faf9f5",
        "on-dark-soft": "#a09d96",
        primary: {
          DEFAULT: "#cc785c",
          hover: "#a9583e",
          light: "#f5f0e8",
          foreground: "#ffffff",
          50: "#faf4f1",
          100: "#f3e4dc",
          200: "#e9cbb9",
          300: "#dcab91",
          400: "#d28e70",
          500: "#cc785c",
          600: "#bd6649",
          700: "#a9583e",
          800: "#8a442f",
          900: "#6b3424",
          950: "#452117",
        },
        secondary: {
          DEFAULT: "#e8a55a",
          500: "#e8a55a",
          600: "#d48f3f",
          foreground: "#141413",
        },
        accent: {
          DEFAULT: "#5db8a6",
          500: "#5db8a6",
          hover: "#4aa38f",
          600: "#4aa38f",
          light: "#eaf5f2",
          foreground: "#ffffff",
        },
        success: {
          DEFAULT: "#5db872",
          500: "#5db872",
        },
        warning: {
          DEFAULT: "#d4a017",
          500: "#d4a017",
        },
        error: {
          DEFAULT: "#c64545",
          500: "#c64545",
        },
        neutral: {
          0: "#ffffff",
          50: "#f8f7f3",
          100: "#efede6",
          200: "#e2ded3",
          300: "#c9c3b5",
          400: "#a39c8d",
          500: "#817a6b",
          600: "#5f594e",
          700: "#47423a",
          800: "#2e2b25",
          900: "#211f1b",
          950: "#181715",
        },
        // Semantic color aliases that work with CSS variables for theme switching
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        surface: "var(--color-surface)",
        "surface-elevated": "var(--color-surface-elevated)",
        "surface-soft": "var(--color-surface-soft)",
        "surface-card": "var(--color-surface-card)",
        "surface-cream-strong": "var(--color-surface-cream-strong)",
        "surface-dark": "var(--color-surface-dark)",
        "surface-dark-elevated": "var(--color-surface-dark-elevated)",
        "surface-dark-soft": "var(--color-surface-dark-soft)",
        border: "var(--color-border)",
        "border-strong": "var(--color-border-strong)",
        "muted-foreground": "var(--color-muted-foreground)",
        ring: "var(--color-ring)",
        ink: "var(--color-ink)",
        body: "var(--color-body)",
        "body-strong": "var(--color-body-strong)",
        muted: "var(--color-muted)",
        "muted-soft": "var(--color-muted-soft)",
        "on-primary": "var(--color-on-primary)",
        "on-dark": "var(--color-on-dark)",
        "on-dark-soft": "var(--color-on-dark-soft)",
        canvas: "var(--color-canvas)",
        coral: "var(--color-coral)",
        "coral-active": "var(--color-coral-active)",
        "accent-teal": "var(--color-accent-teal)",
        "accent-amber": "var(--color-accent-amber)",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        display: ["Cormorant Garamond", "Georgia", "Times New Roman", "serif"],
        mono: ["JetBrains Mono", "SF Mono", "Consolas", "monospace"],
      },
      spacing: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        8: "32px",
        10: "40px",
        12: "48px",
        16: "64px",
        20: "80px",
        24: "96px",
      },
      borderRadius: {
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "20px",
      },
      transitionDuration: {
        micro: "120ms",
        standard: "200ms",
        page: "240ms",
        emphasis: "480ms",
        "3d-camera": "480ms",
      },
      transitionTimingFunction: {
        out: "cubic-bezier(0.4, 0, 0.2, 1)",
        page: "cubic-bezier(0.16, 1, 0.3, 1)",
        emphasis: "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [],
}